# This is a basic workflow to help you get started with Actions

name: Github Action cronjob

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:    
    - cron: "*/30 * * * *"

jobs:
  discord_messages:
    name: Discord Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Post farming messages
        run: |
          python "Discord Farming/discordmsg.py"
